[build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn treasure_hunt.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --log-level info --access-logfile - --error-logfile -"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
