# Generated by Django 4.2 on 2025-07-20 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_name",
                    models.CharField(default="AR Treasure Hunt", max_length=100),
                ),
                ("is_game_active", models.BooleanField(default=True)),
                ("max_players_per_session", models.IntegerField(default=100)),
                ("default_treasure_points", models.IntegerField(default=100)),
                ("default_discovery_radius", models.FloatField(default=50.0)),
                ("leaderboard_refresh_interval", models.IntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Game Configuration",
                "verbose_name_plural": "Game Configurations",
            },
        ),
        migrations.CreateModel(
            name="TreasureTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("points", models.IntegerField()),
                ("discovery_radius", models.FloatField()),
                ("category", models.CharField(default="General", max_length=50)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                            ("EXPERT", "Expert"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_active_template", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Treasure Template",
                "verbose_name_plural": "Treasure Templates",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE_TREASURE", "Created Treasure"),
                            ("EDIT_TREASURE", "Edited Treasure"),
                            ("DELETE_TREASURE", "Deleted Treasure"),
                            ("ACTIVATE_TREASURE", "Activated Treasure"),
                            ("DEACTIVATE_TREASURE", "Deactivated Treasure"),
                            ("CHANGE_SETTINGS", "Changed Game Settings"),
                            ("RESET_LEADERBOARD", "Reset Leaderboard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_treasure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.treasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Action",
                "verbose_name_plural": "Admin Actions",
                "ordering": ["-timestamp"],
            },
        ),
    ]
